### ISSUE TITLE
Function getErrors always returns []

### ISSUE THREAD

**Issue by sfadschm** [tattersoftware/codeigniter4-schemas#12]
https://github.com/tattersoftware/codeigniter4-schemas/blob/eb6d5afeb5be188d6355f3075ae02a4bc5c498b2/src/Schemas.php#L56-L58
I think `$tmpErrors` should be returned, else the function will always return an empty array.

**Comment by MGatner** [comment]
😂 You're very right! Feel free to drop a PR, or I will get to it on the next update.
