### ISSUE TITLE
Help: Many To Many example 

### ISSUE THREAD

**Issue by Noext** [tattersoftware/codeigniter4-schemas#20]
Hello 

it is possible to a many to many relation example ( like this : https://github.com/tattersoftware/codeigniter4-schemas/blob/develop/tests/_support/Schemas/Good/Products.php ) but with a many to many relation like this : https://i.imgur.com/Tp8befQ.png

my database a do not respect naming convention , so i need to override this relation in php 

thanks

**Comment by MGatner** [comment]
Yes. See almost this exact example in the following thread: https://github.com/tattersoftware/codeigniter4-schemas/issues/19

Please use Issues for feature requests and bugs. You can take support requests to the CodeIgniter Forums or request them of me by sponsorship.
