### ISSUE TITLE
PHP 8.1 Fatal error

### ISSUE THREAD

**Issue by internalsystemerror** [tattersoftware/codeigniter4-schemas#33]
Using this on PHP 8.1 I get the following error:

> During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Tatter\Schemas\Reader\Handlers\CacheHandler::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /path-to-project/vendor/tatter/schemas/src/Reader/Handlers/CacheHandler.php:155

**Comment by MGatner** [comment]
Okay I will take a look, or you could send a PR over.

**Comment by internalsystemerror** [comment]
I was going to yesterday but I got stuck trying to fix the PHPCS and PHPStan issues in order to do that so I think I'll let you.
