### ISSUE TITLE
Error: undefined function: plural()

### ISSUE THREAD

**Issue by Schop** [tattersoftware/codeigniter4-schemas#9]
When running "php spark schemas", I get the following error:

`Type:        Error
Message:     Call to undefined function Tatter\Schemas\Drafter\Handlers\plural()
Filename:    C:\xampp\htdocs\euro2021\vendor\tatter\schemas\src\Drafter\Handlers\DatabaseHandler.php
Line Number: 269`

What am I missing?

**Comment by MGatner** [comment]
Not your fault! I conditionally load the `inflector` helper from CodeIgniter core and it looks like I forgot a spot there. You could load it manually first or I should have a fix in place later today.

**Comment by Schop** [comment]
OK, thanks!
